/* XPM */
static xpm_row_t letras[] = {
"374 17 108 2",
"  	c #FFFFFF",
". 	c #FFFFDB",
"+ 	c #B6DBDB",
"@ 	c #DBB68F",
"# 	c #663966",
"$ 	c #666666",
"% 	c #8F8F8F",
"& 	c #668FDB",
"* 	c #8F6666",
"= 	c #668F8F",
"- 	c #663939",
"; 	c #393939",
"> 	c #393966",
", 	c #668FB6",
"' 	c #DBDBFF",
") 	c #B68F8F",
"! 	c #8FB6DB",
"~ 	c #DBFFFF",
"{ 	c #FFFFB6",
"] 	c #66668F",
"^ 	c #8F8FB6",
"/ 	c #DBDBDB",
"( 	c #B6B6B6",
"_ 	c #8FB6B6",
": 	c #668F66",
"< 	c #FFDBDB",
"[ 	c #DBB6B6",
"} 	c #B6DBFF",
"| 	c #B68F66",
"1 	c #8FDBFF",
"2 	c #8F6639",
"3 	c #B66639",
"4 	c #FFDB8F",
"5 	c #B6DBB6",
"6 	c #8F8F39",
"7 	c #000039",
"8 	c #66B6FF",
"9 	c #FFDBB6",
"0 	c #DBDBB6",
"a 	c #B6B666",
"b 	c #390039",
"c 	c #66B6DB",
"d 	c #666639",
"e 	c #390000",
"f 	c #003939",
"g 	c #66B68F",
"h 	c #B6B68F",
"i 	c #000000",
"j 	c #39668F",
"k 	c #39398F",
"l 	c #8F8F66",
"m 	c #396666",
"n 	c #DB8F39",
"o 	c #FFB666",
"p 	c #393900",
"q 	c #66B6B6",
"r 	c #398FDB",
"s 	c #00398F",
"t 	c #000066",
"u 	c #B6FFFF",
"v 	c #8FDBDB",
"w 	c #DBB6DB",
"x 	c #660000",
"y 	c #3966B6",
"z 	c #003966",
"A 	c #B6B6DB",
"B 	c #DBFFDB",
"C 	c #8F3900",
"D 	c #398FB6",
"E 	c #660039",
"F 	c #DBFFB6",
"G 	c #0066B6",
"H 	c #B68FDB",
"I 	c #B66600",
"J 	c #8F6600",
"K 	c #8FDB8F",
"L 	c #666600",
"M 	c #663900",
"N 	c #006666",
"O 	c #396639",
"P 	c #DB8F66",
"Q 	c #8F8FDB",
"R 	c #660066",
"S 	c #8F3966",
"T 	c #B68F39",
"U 	c #DB8FB6",
"V 	c #8F668F",
"W 	c #8F3939",
"X 	c #B6FFDB",
"Y 	c #B6FFB6",
"Z 	c #DB8F8F",
"` 	c #DBB666",
" .	c #8FB68F",
"..	c #DBDB8F",
"+.	c #FFB68F",
"@.	c #B6B6FF",
"#.	c #398F8F",
"$.	c #FFB6B6",
"%.	c #8FB6FF",
"&.	c #B68FB6",
"*.	c #00668F",
"=.	c #8FDBB6",
"-.	c #B6668F",
";.	c #390066",
">.	c #B6DB8F",
",.	c #6666B6",
"'.	c #B66666",
").	c #66398F",
"      . + . @ # $ % $ &         . * $ = $ $ - ; ; ; > , '             . ) $ ; ; $ ! ~     . * $ $ $ $ $ $ $ $ = +       { * $ $ ; $ $ $ ] ^ / / ( * > $ _ * : $ ] ( + < / ' . [ !     [ ( ( % }         . | ; ; > 1         . 2 ; ; > + * $ $ $ 1             3 ; ; ; &     | , ~         4 ; > 5 * 6 7 ; ; ; 8             4 $ $ $ $ $ $ !               9 * $ $ _ | $ $ $ ,           @ $ $ $ !         . @ * $ $ = }         / ~ 0 @ $ % _ a ; ; , '             9 * ; ; > = +         { - > - ; ; ; ; ; ; ; ; , ~           / . ( ( a b c       @ d ; ; > ; ; ; ; > d ; e f b g _ /     < / ( h - > d i 7 j 6 k / [ + ' . l - ; m e 7 ; ; &         n ; ; ; i 7 1     o ; ; p i q 2 r 9 ~ . 3 i i i s ~   3 ; ; p t u   < ~     3 ; ; ; ; ] $ $ $ = 0 ^ | $ v / / / w ~ ",
"          9 h e i $ i t u       { x 7 $ e i i i i i i i i y       . 3 i i i i i i i 7 1   { x i i i i i i i i i i z 1   { x i i i i i i i y < 5 x i i f ; $ ] 2 q ) A B ) ^     . | p i i i 7 p i j ~   . | e i 7 1         . C i 7 : _ x i i i 8             3 : e i D 2 d i r ~       9 E ; i i 7 _ x i i i 8           < F x i i i i i G         . H B | - i i r [ ) 2 ; 7 1         n i i i r     . | e i i D / I i z }     / B ) d i z h e i i i 7 1       . 2 i i i i i i i z !     { x f p i i i i i i i i i 7 1     < J 7 K e i i 7 L z }   I i i f b m e f d i i 7 = M i f i z v / 0 ^ w + n i i i i i i t u         { x i N x i i i G       < C i i i 7 c ~     n i i i i 7 p z $ 8     @ M i i z $ O ; i i i r         4 e i i i G P p i i ; p z M i > , + A     ",
"        0 Q n i i i i i 8       { R L 7 p i i i i i i f i i 8   . C i i i i i i i i i i c { x i i 7 m d e i f e i i 7 1 { E ; e i i i i i s 0 * d p 7 i i i 7 ! B | _ % ^ % } . I i i i i i i i i i 7 1 { S - i 7 1         . T e f p q x i i ; 8             I i i i D C i i i r     { M i ; i 7 8 { x i i i 8             { x i i i i i t u       < 5 ( U l O e D /   9 | e s ~       n i i i r   . 3 ; b ; i z h * $ e 7 1   P d e i i i ; i i i i i 7 1   . C i i i i i i i i i i r   { x i i f e i i i i i i i i t u 4 ] / T D C i i 7 p i 7 8 I f ; d i ; 7 , T i i p i p i i i 7 c ' . ' / . C i m i i i > > 1         4 p i r n i i i s ~     . C i i i 7 1       I i i i D C i i i s ~ { S M i i i i c a e i i 7 c       I i i i 7 1 n i ; e p i i i i i c /       ",
"        { V W 7 p f ; i G       { R L 7 p > $ $ $ - i i ; i s ~ I i i i f 7 > d e i t d i q x i i i i i f i i i i i i t X I O i i f ; d m y B h * p i i i z ! / B [ V % * = } n i i i i i i i i i i i t Y E ; f 7 1           Z - z p q x i i y ~             I i i i D C i i i r   . C i 7 p i 8   { x i i i 8             { x i i i i i i 8       P _ ( 0 | e ; r .   . @ p i 8       n i i i r   3 ; z M f e i i f : e f k ~ T > p z _ ( ( | p i i i y A   I ; i f e i f p i i i i i 8 { x i f e > $ $ $ d i i i i i 8 n t u 4 y 3 $ - i i i i t L i i ; i i i i ; i m ; ; p i i i 7 1       ( { x f e i i i i i G ' < ~ . n r @ ! { x i i 7 1     o i i i i i 8     { x i ; b 1 4 e i i i r . C i i i i G   @ M i i y ~     . A n 7 m &   @ p i i i ; i i i 7 > ! + 0 ' ",
"        . 3 i i i i i i t u     { R 6 7 ; 8         I i i i s ` i i i i c       9 M i i i f e i i 7 1       ` e i i i i j x i i 7 1   . ~         { x i i i 8             / 4 e i i i s J i z 2 i i i ; N x i , * }         . W $  .M q x i i z }             I i i i D C i i i r   I i i i i r   / 0 x i i i 8             { x i i 7 p i i r     . C G 4 b 1 n i D ) v 9 l e i t u   ' n i i i r 4 e i i i z c < / P e i i s ~ I i i t u < ~   . C i i i s ..e i i f k }     9 x i i i s F x i i p r       < 0 x i i i D C G   +.1       { - e f e c A       n i i i y ~     { x i i 7 1     9 @.{ x #.x 7 L i i i s ~     . C 7 l m @.I i i i 8     n i i i i i r     4 e i i s ~   n i i i 7 p i i i i s ~     3 i i > = ~ < ) * c P k ~           $.u   { x s } . /     ",
"        . C i i 7 d i i i r     { R 6 i ; 8         n i i i G I i i i G           . * $ b O e i i f %.        { x i 7 p i i i i i 8   < ~         { x i i i 8           < &.J i i i G   n i s ~ n i 7 d i i i i f 1           @ ^ 3 z X * _ M *.'             I i i i D C i i i D T i i i i j A /   { x i i i 8             { x i i 7 d i i s ~   4 e i i 7 1 I f , % [ A J m - i D w Z 2 i i i r I i i j # 5 &.( '   9 d e t u I i i t u         I i i i s T i 7 p s B '       4 e i i 7 =.x i i i s ~         I i i i D C G { ] V ~       ` m - i r         n i i i s ~ 4 %...e i i 7 1         { x m x 7  .e i i t u     4 e > ; c   n i i i r     I i i i i i s ~   o i i i G     . C i i i f i i i 7 1   9 + ` e i s ) } ..^ ( ' ) u             /   . C 7 ! @ ] ~     ",
"        4 e i i s ..e i i s ~   { R L i i 8       4 e i i 7 =.x i i i 8             < / ' 4 x i i f %.          o i i i i i i i i D ( ( ( ( ( ( ( F x i i i 8             { x i i 7 1   9 M s ~ . ( A 0 h e i > ; ] - j ( | $ ;  .e y F S %.3 i 8       < ~   I i i i #.C 7 ; i ; > p i i r   /     { x i i i 8             { x i i 7  .e i t u   o i i i t X S 6 D % 5 A [ d 7 p 7 l > 2 i i i D C i i z ^ ~ < ~     9 M i t + * : e t u   / &.~ I i i ; *.C i ; i 8           . C i i i #.x i f 7 1   . w ~ { M i i i 8 n r o i i #.V }         -.u         n i i i s ~     { x f e 7 1         { x i i 7 v C i i i 8     o ; e ; G   4 e i i G   . C i i i i i t 1   n i i i 8       4 e i i i i i i G           n ; i = e i z +               . /   . C f b ; i r       ",
"        n i i i r . C i i 7 1   { R L ; i i i i i i i i 7 1 4 e i i t u                   { x i i f %.          { x i i i i i i i i i i i i i i i #.x i i i 7 ; ; ; ; ; >  .e i i t u     4 k ~         { x i i y 0 W , 2 i z ! ..- e 8 ( / C i 8   +.] / ~   I i i i r n ; i i t : , P 7 D         { x i i i 8             { x i i 7 =.x i i 8   I i i G [ B @ e D W c o s B C i i y ~ n i i i #.x i i t u   9 @.      n f ;.a 7 p i t + / / / ` i i i m #.x i i 7 1       < ~   o i i i N x i i i j + ) ( ( J f - i t u . ' n i i *.C i f j }   . '         n f e i s ~     { x i i 7 1         { x i i 7 1 n i i i y     @ ; - j }   . C i i t u { x i z Y x i 7 v ( C i i t u         n i i i i i t u     /     . 3 i i i i G                 . ~   3 f e i i r         ",
"      4 e i i 7 1   n i i i r   { R L m e i i i i i i i i z >.e i i s ~                   { x i i z }           { x i i i i i i i i i i i i i i i #.x i i i i i i i i i 7 l i i i s }       3 ; > 1   P p 7 e i i i f p ; t _ / T e i 8   . C i 8     . ' /   I i i i r n i i 7 O k L i i j @.      { x i i i 8             { x i i 7 1 I i i r . C i i r ~ 9 x i D C i i s ~ I z 5 -.} n i i i #.W e i t u           . 3 > , ` f p f e i i i i i i i i > =.x i i t u     / ~     o i i i N E p i i i i 7 ; 7 ; > e z 1       T i i t L i i i i k } < ~       n i i i s ~     { x i 7 7 1     . ' { x i i 7 1 4 $ * ; r   . C $ ; b 1     I i i 7 1 4 e i s B C i i 8 { x i 7 1           { M i i i ; r       Z  .&   ` i i i 7 ; 8                   P > e i i r           ",
"      o i i i s ~   o i i i t u { x f ; ; ] % % % l ; e i i i i i i t u                   { E p i z }           { x i i i i i i i i i i i i i i i #.x i i i i i i i i i 7  .e i i s ~ /     I i s ~   n i i i i i i D )  .p ; $ i i i = y 5 C i c 0 A < ( +   I i i i y I f ; 1 0 ( d M i i m }     { E p i i 8             { x i i 7 1 n i i s ..e i t u   n i i D C i i r   . J *.+ &.n i i i #.x i i t u             n i s ` f ; e i i i i i 7 p i i 8 { E p i 7 1   . '       I i i i N x i i i i i i ; i i i i r             @ $ d i i i i i s ~         [ % J i s ~     . W m M ; 1       / { x i i 7 1 . C i i s u 4 e p s % ~     o i i i 8 o i i G   I i i r 4 e i i r           n i i i i i s ~     9 5 @.    I i i i 7 1                 n e ; i i G             ",
"      I i i i y / / 0 x i i i 8 { x i i 7 1         4 e i i i i i i i 8           . * $ $ d i i f N @.          4 e i i i i i i i 8   9 ,         { x i i 7 m $ $ $ $ $ ] h e i i t u . /   n i t u   n t l i i z ( }       { M i i i 8 0 # M i , ^ % ] + B ~ I i i i D 3 7 j h }   < % 0 2 e s ~   { x i i i 8             { x i i 7 1 4 e i 7 6 i i s ~ 9 l e i D C i i 8   9 J i r ) T i i i D C i j ( '           . V a # 6 i i i i i i i i i i f c   . W $ i i 8       4 ,.. C i i i #.x i i i i i i i i i i i i G       . w ~   . | e i i i i r         $.u P i s ~     . ) ( - b 1         { x i i 7 1   n i i i 8 o f e ; G       { x i i r I i i r   o i i t 6 i i i r         4 e i i i i i i r     n 7 c     4 e i f D                 o i i i i t } < ~         ",
"    { x i i i i i i i i i i i G { x i i i 8         . C i i i i i i i r           o i i i i i i i *.'           n i i i i i i i i 8   . +         { x i i r   . ~         { x i i i 8   +.%.0 + / /   n 7 $ N x t u < &.}   . C i 7 q ' { # M i m k T G ..j ' I i i i r n 7 : , ( + / h ( 2 7 b c   { x i i i 8             . C i i 7 1 . C i i i i i r   +.> p i D C i 7 _ A / 9 x z d i i i i G I >  ._ A           { % h ] C i f e 7 ! / / / / ~         T e i i *.~   4 e i f e i i 7 =.E ] ^ 2 %.      . I i i i 7  .e f p s /       . C i i i G         < ~ 4 e s ~     . @ x i i & + < + / ..x i i 7 ! / o i i i G I 7 p t }     < B C i i s 3 i i 8   4 e i i i 7 , [ }       . C i i i i i i i 7 1 . / / ~     4 x 7 > u               o i i m e 7 ! / + / '       ",
"    +.p i i i i i i i i i i i t Y x i i i &   . '   { x i i i $ i i i f c '     . C i i i N E g ( ^ ~       . ` e i i i f e i i i 8               { x i i 8                 3 d i i t u 9 - y ~ ` z ! n i ; f i i D &.* & B ' I i i i 8 . * M i i i i t u [ B C i i i r P % - c   <   9  .x i 7 ] 1 { x i i i 8             . '.d i 7 1   I i i i i 7 1   o i i i D C i s 0 A B ' n i i i i i i r o i i i 7 c       9 * - > d f e i i 7 1 . A               o i i i i r   { x i i i i ; t Y E ! ~             { x i i i = b $ i 7 1         n i i i G           { &.M s ~     . | x f e s ~     B n i i i t u < F x i i t : & +.] + '       n i i i i i t u   . C i i i i i *.+       o e i i 7 v C i 7 p s ~ w         ` e i t }             4 e i i i t ! / ~             ",
"    n i i i i j 2 p i 7 > _ ( ( 5 x i i 7 = # = ( l e i i i f ! C i i i i 7 m e i i i i i f ;.% ! [ / h | Q @ p i i i 7  .e i *.h ! 9 | e f ; ; ; p i i i r                 4 e i i i z 5 3 s 6 i i > M i i f p i r / / 0 V 0 e i i i r { # M i i i i i 7 $ e i i i i 8 n j _ C 8       o ; e i i s F x i i i 7 ; ; ; ; ; ; p y l e 7 1   o i i z M s ~   o i i i D C i 7 c B '   . C i i i i i r . C ; f b p 7 m $ > d ; = ).X C i i 7 1                   . C 7 ; i i f $ - i i ; i f & 5 3 i c . ~           I i i i r ( @ 2 i i z = A ` e i i i 8           4 b M s ~       ` b p i i 7 m $ e i ; i i r       I i i i > p ; r           o i i i i i s ~     T i i i i 7 c       4 e ; ; e r   o i i i i r       9 ,.4 e i i s '         { x i i t l f ; ; b ; ; ; k X ' ",
"  < J i i 7 1           ` ,.B | : x i i i i i i i i i i i i t u 9 M i i i i i i i i i i i i i i i i i i i z $ d i i i G { x i D T c | d i i i i i i i e i r           . '     n i i i i i i i i i i 7 p i i i ; i 8   . ' / B ` e i i & { ;.e i i i i i i i i i i i 7 1 n f e i 8       . C i 7 ] l g x i i i i i i i i i i i y ) m - 1   4 e i i ; 7 1 $.` i 7 p D C 7 : b 1 0 '   o i i i i i r   { M i i 7 p i f b p z e r { - e i 7 1                 < ~ { x i i i i i i i i f e > v ' 4 e k B             I i i i r . C 7 O e i i i f e i i s ~           o i i s ~       { M i i i i i i i 7 p i 7 1       o i i i j - e D '         { x i i i i G     / I 7 > =.x 7 1       < A . ( V ~     I i i i r           { x i i c           { x i i ; e i f i i i f p 7 v ' ",
"  9 M i i j ~           9 _ % ^ 6 e i i i i i i i i i i i z 1     . C i i i i i i i i t + a b e i i i p i i i i i i y ~ { x i i i ; i i i i i i i i i i i r                     n i i i i i i i i j M i i i i i i 8 / [ A . ) C i i i 8 . W e i 7 - i i i i i i i 7 8 { C i i z u         { ] 5 J i p ;.d e i i i i i i i i 7 q A [ A     . C ; ; ; 8     o i i i D C i i 7 1       . C i i i i r     { M i i i i i i i D A   4 ;.L i 7 1                       . 2 i i i i i i f e i i s 0 M i j + '           n i i i G   9 M i i i i i i i i j }             I i i s ~         { M i i i i i i , C i r         { x i i i i ; p s ~     / / I i i i i r     9 | i i i i z ^ ~   @ 5 ] 0 = '       4 d e i r '.u     ` M i i t u           { x i ; i i i i i i i i i i z } ",
". ) 2 i i r             . 2 - ; O i ; p i i i i i i 7 ; y ~ . ~   / / 0 W p i i f ] ^ @ ^ ( 2 i i i i i i f $ $ ] !   < a ; e i i i i i i i i i i i i i i r                       9 M i i i i 7 y ~ I ; i i i p t u       . ( C p 7 - q x i i i r . ) M i i i 7 y '   . C i i i r           / h M i i i m % $ ; ; ; ; ; ; ; > c B ' 9 } <   I i i 7 1     o i i i D C i i 7 1         4 e i i i r         9 l e ; ; > ^ ~     9 ).6 i 7 1                           9 l p i i ; = ( x i i , M s T = @.    <     o i i i s ~     < ( | $ $ e 7 y ~             { x i 7 j ~           . @ - i i i 7 y / ~             T ; ; ; ; & [ ~         ) T i i i 7 ^ }   / ..x i i i 7 j } 4 e i i i D           n i i D C G     / ` i ; > 1           { x i i i i f > - e i i i i 7 1 "};
